---
title: "Exercise 1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r}
library(tidyverse)
library(dplyr)
library(igraph)
```

## 1. Downloaded Contact informations from Linkedin

## 2. Import data into R


```{r}
library(readr)
connections <- read_csv("Connections.csv")
head(connections)
```

## 3. Count contacts by current employer


```{r}
connections %>% 
  count(Company) %>% 
  arrange(-n)
```
## 3. Count contacts Total


```{r}
connections %>% 
  count()
```

## 4. Create list of nodes

inspired by 
```{r}
connections = connections %>%  unite(name, c("FirstName","LastName" ))
nodes = connections %>% select(c("name", "Company"))
nodes = nodes %>% rowid_to_column("id")
nodes %>% head(10)
```
## 5. Create list of edges


```{r}

edges = connections %>% select(c(name, Company)) %>% left_join(nodes %>% select(c(id,name)), by = c("name"="name"))
edges = edges %>% left_join(edges, by = "Company", keep=FALSE) %>% select(c("id.x", "id.y", "Company")) %>% filter(id.x!=id.y)

colnames(edges) = c("x", "y", "Company")
edges %>% head(10)
```

## 6. Plot


```{r}
linkedIn_graph = graph_from_data_frame(d=edges,vertices=NULL ,directed=FALSE)
linkedIn_graph
#did not achieve to plot
```