---
title: "Exercise 5: Madness of the crowds"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## What is complex contagion and how it’s different from simple contagion? 
There are two mechanisms of contagion for an idea, a behavior or a disease to spread across individuals in a given network.

The first mechanism is called simple contagion. In this case, one exposure is sufficient to spread the "virus". This mechanism relies on influencers and on infectiousness of the virus. In social networks, it is considered that simple contagion is what helps spread headlines and catchy messages. However; as noted by Centola, "We are in a world where catchy ideas spread quickly but have no lasting impact".

Complex contagion is a mechanism that allows for longer lasting changes. It requires several exposures to an innovation or idea to spread its adoption and lastingly change behaviors. For this mechanism to work, a certain ratio of "infected connections" needs to be reached as compared to the total number of connections of a given individual, for this individual to get infected. This inidividual may have several "friends" who are infected, but as long as the proportion of friends is below the threshold, the individual will not get "infected" by the new behavior.


## What does complex contagion mean for diffusion of behaviors in organizations?

Social change is about changing beliefs and behaviors. We change behavior if we feel guided by our social networks, so our connections shape how we respond to innovation. Considering successful social change is about norms more than it is about information, complex contagion is a better model for diffusion of behaviors in organizations than simple contagion.  

To illustrate this process, Centola refers to the adoption of Twitter and the influence of Oprah Winfrey in the process. While many consider Oprah Winfrey using Twitter in front of her audience drove the growth of Twitter users. But the complex contagion model states that a large share of Oprah's contacts were using Twitter, and promoted her to start using it.  

We are influenced by the proportion of the people we know who are doing something, rather by the actual number. In this sense, the more popular you are, the more wary you are of adopting an innovation because it may take longer for you to be surrounded by a large proportion of innovators. It is also important to be careful about group think, as you are less likely to adopt new ideas when surrounded by people who think like you. 

Factors that can influence the diffusion of behaviors in organizations, include the number of connections who have adopted the change, those who have not adopted it, and also the attributes of each individuals as disposition to adopt change.


## How can we use the threshold models to better manage prosocial behavior in organizations, learning and toxic behaviors?

In complex contagion, the threshold value for an individual to adopt change is the ratio of connections that have adopted the change versus the connections who have not adopted it. 
To promote good behavior, we need to estimate the contagion threshold in the network (assuming it is the same at network level) at which innovation spreads. Then we can organize the network in such a way that enough % of people with good behavior will be in touch with each individuals, by increasing the number of individuals with good behaviors in the network, and establishing connections with target individuals starting by those with less connections. It is necessary to optimize the solution to reach the threshold without exceeding number of connections, using a mix of bonding social capital (connections within a group) and bridging social capital (connections between different groups). Learning can be promoted by looking also at the attributes of individuals, in particular level of skills.

To manage toxic behaviors, we need to decrease the ratio of connections with bad behaviors, this can be done either by breaking connections, or increasing the number of nodes with good behaviors in contact with the infected people so to reverse the proportion and foster good behaviors.

### Sources of information
Centola; The “explainable” at https://ncase.me/crowds/
